import {
  getCenaivaImmediateFiller,
  isCenaivaProcessPrompt,
} from '@/lib/cenaiva/simplePromptIntent';

const PROMPT_GROUPS = {
  randomOffTopic: [
    'Do you think fish get thirsty?',
    'What would happen if I brought a raccoon to dinner?',
    'Can I book a table for me and my imaginary friend?',
    "What's your favourite dinosaur?",
    'If pasta could talk, what would it say?',
    'Do restaurants allow ghosts?',
    'Can you help me win an argument?',
    'Is cereal soup?',
    "What's the meaning of life?",
    'Do you believe in aliens?',
    'Can you roast me before I book?',
    'Tell me something dramatic.',
    'Would you rather fight one horse-sized duck or 100 duck-sized horses?',
    'Can I reserve a table under the name Batman?',
    'What if I show up dressed like Spider-Man?',
    'Do you think chairs have feelings?',
    'Can the restaurant dim the lights just for my villain entrance?',
    'Can I bring a fog machine?',
    'Is it weird to eat fries with a fork?',
    'Can you pretend this is a spy mission?',
  ],
  weirdBooking: [
    'Book me the most mysterious table available.',
    'I want a table where no one can perceive me.',
    'Reserve a table with maximum drama.',
    'I need a table for a breakup but make it classy.',
    "Book a table for 2, but emotionally it's for 9.",
    'I want the table with the best escape route.',
    'Can I sit somewhere that makes me look important?',
    "I need a table where my ex won't see me.",
    "Book me somewhere that says 'I have my life together.'",
    'I want a table that screams rich but whispers humble.',
    'Can you book me a table near the bread?',
    'I want a table far from children, chaos, and soup.',
    'Reserve me a seat where I can judge everyone quietly.',
    'Book me a table that feels like a movie scene.',
    'Can I get a table where I look mysterious?',
    'I want a romantic table but not too romantic.',
    'Book a table for my situationship.',
    'Can you find a table for people who are definitely not on a date?',
    'I need a table for a dinner that may become an argument.',
    'Book something that makes me look like I planned ahead.',
  ],
  jokes: [
    "I'm only going if the bread is emotionally supportive.",
    'I need a table before I become hangry.',
    'This reservation determines my entire future.',
    "If they don't have fries, I'm leaving society.",
    'I need a table for me and my bad decisions.',
    "I'm bringing vibes, not money.",
    'Can you make sure the chair respects me?',
    "I want a table where I can eat like nobody's watching.",
    'Book it before I change my personality.',
    'I need dinner before I text my ex.',
    'I am not hungry, I am spiritually empty.',
    'Can the restaurant clap when I enter?',
    'I want to sit where the lighting fixes my face.',
    'Book me somewhere my outfit can be appreciated.',
    'I need a table with main character energy.',
    'This booking is a government emergency.',
    'Can they spell my name wrong in a fancy way?',
    'I need a table for 3 people and 14 unresolved issues.',
    'Make sure the vibes are immaculate.',
    "I want the table to know I'm coming.",
  ],
  vague: [
    'Dinner.',
    'Table.',
    'Tonight maybe.',
    'You know what I mean.',
    'Book the usual.',
    'Something nice.',
    'Not too late.',
    'For a few people.',
    'Somewhere downtown.',
    'Make it good.',
    'I need food.',
    'Can you handle it?',
    'Whatever works.',
    'Surprise me.',
    'A place with vibes.',
    "I'm thinking Friday.",
    'Maybe 7 or 8.',
    'Near me.',
    'For us.',
    'You choose.',
  ],
  impatient: [
    'Hurry up.',
    'Why is this taking so long?',
    'Just book it.',
    'Stop asking questions.',
    'I already told you.',
    'Can you be faster?',
    "I don't care, just pick.",
    'Do it now.',
    "I'm starving.",
    'This better work.',
    "Don't make this complicated.",
    'I have 10 seconds.',
    'Skip the questions.',
    "You're moving slow.",
    'Just get me a table.',
    "I don't want a whole conversation.",
    'Book anything available.',
    'Fastest option please.',
    'Why do you need all that info?',
    'Less talking, more booking.',
  ],
  emotional: [
    "I'm having a terrible day.",
    'I need a table before I cry.',
    "I'm nervous for this date.",
    'This is my anniversary and I forgot.',
    'I messed up and need a reservation fast.',
    "I'm planning a proposal.",
    'I just got dumped, book me something nice.',
    "I need a quiet table. I'm overwhelmed.",
    "I'm taking my parents out and I'm stressed.",
    "It's my birthday but nobody planned anything.",
    'I want to impress someone.',
    'This dinner is important.',
    "I don't know where to go.",
    "I'm anxious about calling restaurants.",
    'Please just make this easy.',
    'I need something private.',
    "I don't want a loud place.",
    'I want somewhere calm.',
    "I'm trying to fix an argument.",
    'I need a table that feels special.',
  ],
  boundaries: [
    'Can you do my homework first?',
    'Can you write me a rap before booking?',
    'Can you order me a car?',
    'Can you call my ex?',
    'Can you hack the restaurant system?',
    "Can you get me a table even if they're fully booked?",
    "Can you lie and say I'm famous?",
    'Can you make them give me free food?',
    "Can you pretend I'm the owner?",
    'Can you threaten them if they say no?',
    "Can you book under someone else's name?",
    'Can you get me a reservation without giving my details?',
    'Can you make a fake phone number?',
    'Can you bypass the waitlist?',
    "Can you make them cancel someone else's booking?",
    'Can you guarantee the best table?',
    "Can you tell them I'm a celebrity?",
    'Can you get me a discount?',
    "Can you change someone else's reservation?",
    "Can you book 10 restaurants and I'll choose later?",
  ],
  policy: [
    'Can I bring a dog?',
    'Do they allow kids?',
    'Is there parking?',
    'Do they have vegan food?',
    'Is it wheelchair accessible?',
    'Can I request outdoor seating?',
    'Can I sit at the bar?',
    'Can I bring a birthday cake?',
    'Do they split bills?',
    'Is there a dress code?',
    'Do they have halal options?',
    'Do they have gluten-free options?',
    'Can I request a booth?',
    'Can they handle allergies?',
    'Do they have high chairs?',
    'Is it loud inside?',
    'Can I bring balloons?',
    'Do they charge for no-shows?',
    'Is there a deposit?',
    'Can I change the booking later?',
  ],
  dateTime: [
    'Book me for tomorrow.',
    'I need Friday night.',
    'Next weekend.',
    'Tonight around 8ish.',
    'As soon as possible.',
    'Late dinner.',
    'Early dinner.',
    'Lunch tomorrow.',
    'Brunch Sunday.',
    'Saturday but not too late.',
    'Anytime after work.',
    'Before the movie.',
    'After 9.',
    'Between 6 and 7.',
    'The earliest available.',
    'The latest available.',
    'Around sunset.',
    'In an hour.',
    'For May 10.',
    'For my birthday next month.',
  ],
  partySize: [
    'Table for 2.',
    'It might be 4 or 5.',
    "There's like 8 of us.",
    'For a big group.',
    'Just me.',
    'Me plus one.',
    'For my family.',
    'For 12 people.',
    'For 2 adults and 3 kids.',
    'For a date.',
    'For a work dinner.',
    'For my team.',
    'For a party.',
    'For a double date.',
    'For whoever shows up.',
    'Maybe 6, maybe 7.',
    'Can I add people later?',
    'Can I reduce the number later?',
    'Book for 10 but maybe 15.',
    "I don't know yet.",
  ],
  payment: [
    'Do I have to pay now?',
    'Is there a booking fee?',
    'Can I pay at the restaurant?',
    'Why is there a service fee?',
    'Can I avoid the fee?',
    'Does the deposit go toward the bill?',
    'Can I split the deposit?',
    'Is my card charged now?',
    'What if I cancel?',
    'Do I get a refund?',
    'Can I pay cash?',
    'Why do they need my card?',
    'Is the reservation free?',
    'Do I need to prepay?',
    'Can someone else pay?',
    'Will the restaurant see my card?',
    'Is tax included?',
    'Is tip included?',
    "What happens if I don't show up?",
    'Can I change the payment method?',
  ],
  foodPreference: [
    'I want Italian.',
    'Something with sushi.',
    'No seafood.',
    'Vegetarian options.',
    'Somewhere with steak.',
    'I want cheap food.',
    'I want fancy food.',
    'Best dessert place.',
    'Somewhere spicy.',
    'No spicy food.',
    'Good pasta.',
    'Good burgers.',
    'Healthy options.',
    'Late-night food.',
    'A place with mocktails.',
    'A place with good cocktails.',
    'A quiet café.',
    'A brunch spot.',
    'A family restaurant.',
    'Something romantic.',
  ],
  changingMind: [
    'Actually make it 8.',
    'Change it to tomorrow.',
    'Never mind, do Saturday.',
    'Can we make it for 4 people instead?',
    'I want a different restaurant.',
    'Can we do earlier?',
    'Can we do later?',
    'Actually I need outdoor seating.',
    'Forget that, make it indoors.',
    'Cancel that.',
    'Start over.',
    'I changed my mind.',
    'Make it cheaper.',
    'Make it fancier.',
    'Actually not Italian.',
    'Can we switch to sushi?',
    'I need it closer.',
    'Make it downtown.',
    'Actually I want takeout.',
    "I don't need a booking anymore.",
  ],
  confirmation: [
    'Is it booked?',
    'Are we good?',
    'Did you confirm it?',
    "What's the reservation under?",
    'Can you send me the details?',
    'What time did we book?',
    'Where is it?',
    'How many people?',
    'Can I show them this?',
    "What if they don't have my booking?",
    'Can you remind me?',
    'Can I edit it?',
    'Can I cancel?',
    'Do I need ID?',
    'Do I need to arrive early?',
    'How long will they hold the table?',
    'Can I be late?',
    'Can I call the restaurant?',
    "What's the confirmation number?",
    'Send me the booking summary.',
  ],
} as const;

const ALL_PROMPTS = Object.values(PROMPT_GROUPS).flat();

describe('Hey Cenaiva small prompt coverage', () => {
  it('covers the full supplied 280-prompt set', () => {
    expect(ALL_PROMPTS).toHaveLength(280);
    expect(new Set(ALL_PROMPTS.map((prompt) => prompt.toLowerCase())).size).toBe(280);
  });

  it('keeps small prompts on the dynamic orchestrator path without local filler', () => {
    for (const prompt of [
      'Do you think fish get thirsty?',
      "What's your favourite dinosaur?",
      'Is cereal soup?',
      "What's the meaning of life?",
      'Do you believe in aliens?',
      'Can you do my homework first?',
      'Can you write me a rap before booking?',
      'Can you order me a car?',
      'Can you call my ex?',
      'Can you hack the restaurant system?',
      'Am I gay?',
      "You're cute.",
      'Hurry up.',
      'Why is this taking so long?',
      'Stop asking questions.',
      'Can you be faster?',
      'Do it now.',
      "You're moving slow.",
      "I don't want a whole conversation.",
      'Why do you need all that info?',
      'Less talking, more booking.',
    ]) {
      expect(isCenaivaProcessPrompt(prompt)).toBe(false);
      expect(getCenaivaImmediateFiller(prompt)).toBeNull();
    }
  });

  it('keeps booking, restaurant policy, and food preference prompts on the process path', () => {
    const missing: string[] = [];
    for (const prompt of [
      ...PROMPT_GROUPS.weirdBooking,
      ...PROMPT_GROUPS.vague,
      ...PROMPT_GROUPS.policy,
      ...PROMPT_GROUPS.dateTime,
      ...PROMPT_GROUPS.partySize,
      ...PROMPT_GROUPS.payment,
      ...PROMPT_GROUPS.foodPreference,
      ...PROMPT_GROUPS.changingMind,
      ...PROMPT_GROUPS.confirmation,
    ]) {
      if (!isCenaivaProcessPrompt(prompt)) missing.push(prompt);
    }
    expect(missing).toEqual([]);
  });

  it('allows immediate filler only for tool-like process prompts', () => {
    expect(getCenaivaImmediateFiller('Find Italian restaurants near me.')).toMatch(/find spots/i);
    expect(getCenaivaImmediateFiller('What times are available?')).toMatch(/check the times/i);
    expect(getCenaivaImmediateFiller('Show me the menu.')).toMatch(/pull that up/i);
    expect(getCenaivaImmediateFiller('Table for 2.')).toBeNull();
    expect(getCenaivaImmediateFiller('What time is it?')).toBeNull();
  });
});
