project_id = "exbjodmnpdiayfzrdyux"

[functions.cenaiva-orchestrate]
verify_jwt = false

[functions.cenaiva-availability]
verify_jwt = false

[functions.cenaiva-small-prompt]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.register-restaurant-owner]
verify_jwt = false

[functions.prepare-phone-login]
verify_jwt = false

[functions.delete-account]
verify_jwt = true
