// Cenaiva Restaurant Partner Agreement v2.1 — canonical text shipped
// 2026-05-21. Verbatim from user-provided canonical content.

import type { LegalSection, SubProcessor, AgreementHistoryEntry } from './types';
import {
  PARTNER_AGREEMENT_VERSION,
  PARTNER_AGREEMENT_EFFECTIVE_DATE,
  PARTNER_AGREEMENT_LAST_UPDATED,
} from './versions';

export {
  PARTNER_AGREEMENT_VERSION,
  PARTNER_AGREEMENT_EFFECTIVE_DATE,
  PARTNER_AGREEMENT_LAST_UPDATED,
};

export const PARTNER_AGREEMENT_INTRO =
  'This Restaurant Partner Agreement (the "Agreement") governs your access to and use of the Cenaiva platform as a restaurant operator or owner ("Restaurant Partner", "you", "your"). This Agreement is between you and Cenaiva ("Cenaiva", "we", "our", "us").\n\nBy registering as a restaurant partner, accepting this Agreement in the app, or allowing Cenaiva to create an account on your behalf, you agree to be bound by these terms. Electronic acceptance through the Platform is binding and enforceable under the Electronic Commerce Act, 2000 (Ontario) and equivalent legislation. If you are agreeing on behalf of a business, you represent that you have the authority to bind that business to this Agreement.\n\nConsumer diners are subject to a separate Terms of Service available at https://cenaiva.com/terms and a separate Privacy Policy available at https://cenaiva.com/privacy.\n\nPrior versions of this Agreement are available at https://cenaiva.com/partners/agreement-history.';

export const PARTNER_AGREEMENT_SECTIONS: LegalSection[] = [
  {
    heading: '1. Definitions',
    paragraphs: [
      "• \"Billing Cycle\" means a recurring monthly period beginning on the anniversary of your subscription activation date (or, for Trial accounts, the date the Trial Period ends), running through the same day of the following calendar month.",
      '• "Booking" means a reservation, waitlist entry, or table request made by a Diner through the Platform.',
      '• "Business Day" means any day other than a Saturday, Sunday, or statutory holiday observed in the Province of Ontario.',
      "• \"Confirmed Booking\" means a reservation request that has been accepted by the Restaurant Partner (whether automatically or manually) and not cancelled by the Diner more than 24 hours before the reservation time measured in the restaurant's local time zone. No-shows are billable as Confirmed Bookings.",
      '• "Deposit" means an amount collected from a Diner through Stripe at the time of booking to secure a Confirmed Booking, and held against no-show or late-cancellation policies set by you.',
      '• "Diner" means a consumer or end user of the Cenaiva consumer app, who is subject to the consumer Terms of Service.',
      '• "Partner Content" means menu content, photos, descriptions, marks, and other materials you upload to the Platform.',
      '• "Partner Dashboard" means the restaurant-facing interface used to manage bookings, menus, floor plans, staff, CRM, and analytics.',
      '• "Platform" means the Cenaiva mobile application, web dashboard, edge functions, and related services made available to restaurant partners.',
      '• "Pre-Order" means a food or beverage order placed by a Diner through the Platform prior to or in connection with a Booking.',
      '• "Pre-Order Fee" means the per-transaction platform fee Cenaiva charges on Pre-Order subtotals, set out in Section 5.1.',
      "• \"Sub-Processor\" means a third-party service provider that processes personal information on Cenaiva's behalf in delivering the Platform, as listed in Schedule A.",
      '• "Subscription Fee" means the monthly fee payable for access to the Platform.',
      '• "Trial Period" means the complimentary three-month period of platform access described in Section 4, available only to qualifying early signups.',
    ],
  },
  {
    heading: '2. Platform Access and Services',
    paragraphs: [
      "Subject to this Agreement, Cenaiva grants you a non-exclusive, non-transferable, revocable licence to access and use the Platform for the purpose of managing your restaurant's reservations, floor operations, guest relationships, menus, and related business functions in Canada.",
      'The Platform includes access to the following features, subject to your subscription tier and availability:',
      '• Reservation, booking, and waitlist management, including Diner-paid Deposits for no-show protection',
      '• Floor plan, table, and section management',
      '• Guest CRM and diner profiles, including Cenaiva-generated tags, no-show risk scores, and lifetime value estimates',
      '• Menu, modifier, and Pre-Order management',
      '• Team and staff access management, with optional biometric authentication (Face ID, Touch ID, or fingerprint) and an optional biometric confirmation step for sensitive actions such as approvals and transfers',
      '• Analytics, reporting, and kitchen display (KDS) views',
      '• AI-assisted guest communication and operational features where available',
      '• Mobile crash and error reporting, sign-in audit events, and new-device security alerts',
      "Cenaiva reserves the right to modify, add, or remove platform features at any time. Cenaiva will give at least 30 days' notice before removing or materially restricting any feature you are actively using, except where shorter notice is required for security, legal, or safety reasons.",
      "The Subscription Fee includes unlimited staff accounts per location at current subscription tiers. Cenaiva reserves the right to introduce staff-seat-based pricing in the future on at least 30 days' notice under Section 5.4.",
      'Future POS integrations. Any future integration between the Platform and a third-party POS, KDS hardware, or in-venue payments system will be governed by a separate addendum to this Agreement.',
      "Cenaiva warranty. Cenaiva warrants that it will perform the Services in a workmanlike manner consistent with industry standards for comparable SaaS platforms and in material compliance with applicable laws. Cenaiva's sole liability and your sole remedy for breach of this warranty is correction of the non-conforming service or, where correction is not commercially reasonable, termination of this Agreement and a pro-rata refund of prepaid Subscription Fees.",
      'Non-exclusivity. Nothing in this Agreement prevents you from using competing reservation, waitlist, or restaurant-management platforms concurrently with the Platform.',
    ],
  },
  {
    heading: '3. Account Setup and Onboarding',
    paragraphs: [
      'Restaurant partner accounts may be created in one of two ways:',
      '• Self-serve — you register directly through the Platform by completing the restaurant onboarding flow and saving a card for billing after the Trial Period.',
      '• Cenaiva-assisted — in some cases, a Cenaiva team member may create your account on your behalf using information you have provided.',
      'In both cases, you are responsible for ensuring that all information provided — including restaurant name, address, contact details, menu content, allergen information, operating hours, and billing details — is accurate, complete, and kept up to date.',
      'You are responsible for all activity that occurs under your account, including activity by staff members you have granted access. You must notify us immediately at help@cenaiva.com if you suspect unauthorized access to your account.',
      'There is no manual approval process for new restaurant partners. By completing registration, you confirm that you are authorized to operate the restaurant and to enter into this Agreement. Cenaiva reserves the right to verify your authority to operate the listed restaurant at any time. Verification may include requesting copies of business registration, food premises licensing, government-issued ID of the signing authority, or proof of address. Cenaiva will treat documents submitted for verification as Confidential Information under Section 12. Failure to respond to a verification request within a reasonable time may result in suspension of your account.',
      'Multi-location restaurants. Each restaurant location is treated as a separate account with its own Subscription Fee. Volume discounts and chain agreements are available by separate written arrangement — contact help@cenaiva.com.',
    ],
  },
  {
    heading: '4. Free Trial and Auto-Renewal',
    paragraphs: [
      'For a limited promotional period, the first 500 qualifying restaurant partners to register receive a complimentary Trial Period of three (3) months from the date of account activation. The promotional cap is enforced server-side. After the cap is reached, new signups are charged the Subscription Fee from the first billing cycle, and the Trial Period is not available unless we publish updated terms.',
      'During the Trial Period:',
      '• The monthly Subscription Fee is waived',
      '• The Per-Booking Platform Fee and Pre-Order Fee described in Section 5 still accrue but are not billed during the Trial Period',
      '• All platform features available under the standard subscription are accessible',
      '• You may cancel at any time during the Trial Period without charge',
      'Auto-renewal disclosure. At the end of the Trial Period, your account will automatically transition to a paid monthly subscription and your saved card will be charged the Subscription Fee at the start of each subsequent Billing Cycle on a continuing basis until you cancel. We will notify you by email at least 7 days before your Trial Period ends, and a reminder of your next billing date is available in the Partner Dashboard at all times.',
      'If you do not wish to continue after the Trial Period, you must cancel your subscription before the Trial Period expires to avoid being charged.',
    ],
  },
  {
    heading: '5. Fees and Billing',
    paragraphs: [
      '5.1 Fee Structure',
      'The following fees apply to your use of the Platform:',
      '• Monthly Subscription Fee — CAD $199.99 per month, billed at the start of each Billing Cycle in CAD.',
      '• Per-Booking Platform Fee — CAD $1.00 per Confirmed Booking made through the Cenaiva consumer app, tracked per restaurant in our platform fee ledger and reconciled on each Billing Cycle.',
      '• Pre-Order Fee — 5.5% of the Pre-Order subtotal (before taxes, tips, and Diner-side service fees) for each Pre-Order placed through the Platform. The Pre-Order Fee is calculated per order at the time the Pre-Order is captured and aggregated into your monthly invoice.',
      "Deposits, gift cards, and event tickets do not currently carry a separate Cenaiva fee. Cenaiva reserves the right to introduce additional transaction-based fees in the future with at least 30 days' written notice as described in Section 5.4.",
      'All fees are exclusive of applicable taxes (GST/HST/QST/PST) unless otherwise stated. Applicable taxes will be displayed at the time of billing.',
      '5.2 Billing, Payment, and Tax Treatment',
      "• All fees are processed through Stripe. By accepting this Agreement, you agree to Stripe's Terms of Service.",
      '• You authorize Cenaiva to charge your nominated payment method on a recurring basis for the Subscription Fee, Per-Booking Platform Fees, and Pre-Order Fees.',
      '• Per-Booking Platform Fees and Pre-Order Fees are aggregated and billed on a monthly basis alongside the Subscription Fee.',
      '• It is your responsibility to ensure your payment method remains valid and up to date.',
      '• Stripe-generated invoices and receipts are available to you through the Stripe customer portal linked from the Partner Dashboard.',
      '• Tax treatment. Cenaiva acts as principal for the Subscription Fee, Per-Booking Platform Fee, and Pre-Order Fee, and is responsible for collecting and remitting applicable GST/HST and provincial sales taxes on those amounts. Where Cenaiva collects Deposits or other amounts on your behalf, Cenaiva acts as your agent, and you remain responsible for the tax treatment of those amounts in your own books and filings.',
      '5.3 Late Payment',
      'If a payment fails or is not received by the due date:',
      '• We will notify you by email and Stripe will automatically attempt to reprocess the payment per its standard retry schedule.',
      '• If payment is not received within 7 days of the failed attempt, we reserve the right to suspend your access to the Platform until payment is resolved.',
      '• Continued non-payment beyond 30 days may result in termination of your account in accordance with Section 14.',
      '5.4 Fee Changes',
      "Cenaiva reserves the right to modify the fee structure at any time. We will provide at least 30 days' written notice before any fee changes take effect. Your continued use of the Platform after the effective date of a fee change constitutes acceptance of the new fees. If you do not accept the new fees, you may cancel your subscription before the change takes effect.",
      '5.5 No Pause Option',
      'Subscriptions are either active or scheduled for cancellation at the end of the current Billing Cycle. There is no option to pause a subscription. If you cancel, your access will continue until the end of the current paid Billing Cycle, after which it will be deactivated.',
      '5.6 Cancellation and Refunds',
      '• You may cancel your subscription at any time by contacting help@cenaiva.com or by removing your restaurant from the Partner Dashboard, which cancels your Stripe subscription at the end of the current Billing Cycle.',
      '• Upon cancellation, your access will remain active until the end of the current paid Billing Cycle.',
      '• Monthly Subscription Fees are non-refundable once a Billing Cycle has commenced.',
      '• Per-Booking Platform Fees and Pre-Order Fees already incurred are non-refundable.',
      '• If Cenaiva terminates your account for a violation of this Agreement, no refund will be issued for any fees paid.',
      '• If Cenaiva terminates your account without cause under Section 14.7, Cenaiva will refund a pro-rata portion of any prepaid Subscription Fee for the unused portion of the current Billing Cycle. Refunds will be processed within 10 Business Days to the original payment method.',
      '5.7 Deposits, Refunds, Chargebacks, and Payment Disputes',
      "Cenaiva may collect Deposits from Diners on your behalf at the time of booking to enforce your stated no-show or late-cancellation policy. Deposits collected through the Platform are held by Cenaiva (via Stripe) and are refunded or retained according to your published policy. Refund requests submitted through the Platform are routed through Cenaiva's refund request queue and resolved by Cenaiva support.",
      'Where a Pre-Order is fully refunded to the Diner before fulfillment, the corresponding Pre-Order Fee is reversed in the same Billing Cycle. Pre-Order Fees on partially refunded, no-show, or late-cancelled Pre-Orders remain payable.',
      'If a Diner disputes a charge, requests a refund, or initiates a chargeback related to a Booking, Pre-Order, Deposit, or restaurant-provided service, you are responsible for cooperating with Cenaiva and Stripe to resolve the dispute.',
      'Where a refund, chargeback, or payment reversal is caused by your cancellation, failure to honor a Booking, failure to fulfill a Pre-Order, inaccurate pricing, or service issue, Cenaiva may recover the applicable amount by deducting it from amounts otherwise owed to you, by adjusting future invoices, or by charging the payment method on file.',
      "Cenaiva platform fees remain payable except where the issue was caused by a verified technical error on Cenaiva's part or where required by applicable law.",
      'Dispute fees. Stripe charges a per-dispute fee on each chargeback (currently CAD $15.00) regardless of the outcome. Where the chargeback is caused by your action or inaction, Cenaiva will recover the Stripe dispute fee from you in the same manner as other reversed amounts. Where the chargeback arises from a verified Cenaiva error, Cenaiva will absorb the dispute fee.',
      '5.8 Merchant of Record and Payouts',
      "Cenaiva is the merchant of record for all charges processed through the Platform — including Subscription Fees, Per-Booking Platform Fees, Pre-Order Fees, Deposits, gift cards, and event tickets. The Platform does not currently route the price of a meal, Pre-Order, or in-venue charge into a Restaurant Partner's bank account. You remain responsible for in-venue payment processing through your own POS, terminal, and merchant of record.",
      'If Cenaiva later introduces a payouts feature (for example, via Stripe Connect), it will be governed by an additional notice and acceptance, and this Section will be updated accordingly.',
      '5.9 Referrals — Refer & Earn',
      'Cenaiva offers an owner-side referral program. When a new restaurant partner signs up using your referral code (format CNV-OWNER-XXXXXX), both you and the referred restaurant receive 30 additional days of free Platform access, applied as a credit to your next Billing Cycle. Referral abuse — including self-referrals, fake businesses, or chained signups intended to evade billing — will result in forfeiture of credits and may result in termination under Section 14.',
    ],
  },
  {
    heading: '6. Restaurant Obligations',
    paragraphs: [
      'As a restaurant partner, you agree to:',
      '• Maintain accurate, complete, and up-to-date menu information, pricing, allergen details, dietary labels, and operating hours on the Platform at all times.',
      '• Honor all Confirmed Bookings made through the Platform, including Pre-Orders and Deposits, in accordance with your published policy.',
      '• Treat Diners with respect and in compliance with all applicable laws, including the Ontario Human Rights Code and equivalent provincial legislation.',
      '• Comply with all applicable food safety, health, licensing, and regulatory requirements in your jurisdiction.',
      '• Maintain commercial general liability insurance with a minimum of CAD $2,000,000 per occurrence and CAD $5,000,000 aggregate, plus product liability coverage appropriate for food service, and provide a certificate of insurance on request.',
      '• Ensure that staff members with Platform access are aware of and comply with this Agreement, including any biometric-authentication or sensitive-action workflows.',
      '• Revoke Platform access immediately for any staff member who leaves your employ or whose access is no longer required. Cenaiva is not liable for unauthorized access by current or former staff that you failed to deprovision.',
      '• Respond to Diner complaints and disputes in good faith and in a timely manner.',
      '• Notify Cenaiva promptly of any issues that may affect your ability to honor Bookings, including closures, capacity changes, or technical problems.',
      '• Not use the Platform or Diner data for any purpose outside of legitimate restaurant operations, and not use Diner data accessed through the Platform to build or operate a competing reservation, booking, or restaurant-discovery platform.',
      'No circumvention. You agree not to (a) divert Diners who first contacted you through the Platform to bookings made outside the Platform for the purpose of avoiding the Per-Booking Platform Fee or Pre-Order Fee, (b) discriminate against Diners booking through the Platform compared to other booking channels, or (c) use contact information shared by Cenaiva under Section 10.3 to solicit those Diners to book outside the Platform for the same restaurant. Cenaiva may audit transaction patterns and, where circumvention is identified, recover the corresponding platform fees by invoice or by charging the payment method on file.',
    ],
  },
  {
    heading: '7. Menu Accuracy and Allergen Liability',
    paragraphs: [
      'You are solely responsible for the accuracy, completeness, and currency of all menu content, ingredient lists, allergen information, dietary labels, and pricing that you provide to Cenaiva for display on the Platform.',
      'Cenaiva displays this information as provided by you and does not independently verify its accuracy. You acknowledge and agree that:',
      '• Any harm, injury, allergic reaction, or loss suffered by a Diner as a result of inaccurate, incomplete, or misleading allergen or menu information is solely your responsibility.',
      '• Cenaiva is not liable for any claim arising from menu or allergen information provided by you.',
      '• You will indemnify and hold harmless Cenaiva from any claim, loss, liability, or expense arising from inaccurate food, allergen, or dietary information you have provided to the Platform.',
      "You must update your menu and allergen information promptly whenever your offerings change in a way that could affect a Diner's safety or purchasing decision. If you become aware of an error in your listed information that could affect Diner safety, you must notify us immediately at help@cenaiva.com so that the relevant information can be flagged or removed pending correction.",
    ],
  },
  {
    heading: '8. Alcohol and Restricted Items',
    paragraphs: [
      "You are solely responsible for complying with all applicable alcohol, liquor, age-verification, licensing, and restricted-product laws in your jurisdiction. This includes ensuring that Pre-Orders involving alcohol or other age-restricted products are only fulfilled in compliance with applicable law. Cenaiva does not independently verify a Diner's legal eligibility to purchase or consume alcohol or other restricted items unless a specific age-verification feature is expressly provided by the Platform.",
    ],
  },
  {
    heading: '9. Diner Relationships and Independent Responsibility',
    paragraphs: [
      'Cenaiva is a technology platform that connects Diners with restaurants. Cenaiva is not a party to any agreement between you and a Diner. You are solely responsible for:',
      '• The dining experience you provide to Diners',
      '• Fulfilling Pre-Orders and honoring Deposits',
      '• Any dispute arising between you and a Diner regarding food, service, pricing, cancellations, or refunds',
      '• Your own cancellation, no-show, and refund policies, which must be clearly communicated to Diners at the time of booking',
      'Cenaiva may facilitate communication between you and Diners but has no obligation to mediate or resolve disputes between you. Repeated failure to honor Bookings, excessive Diner complaints, or patterns of poor service may result in suspension or removal from the Platform.',
    ],
  },
  {
    heading: '10. Data, Privacy, and Security',
    paragraphs: [
      '10.1 Data Controller Structure',
      'Each party is an independent data controller with respect to personal information it processes in connection with the Platform. Depending on the specific data and feature involved, the parties may also act as service providers or processors under applicable privacy laws. In summary:',
      '• Cenaiva is responsible for personal information it collects from Diners through the consumer app, including account data, voice and chat interactions, payment data, Deposits, AI-generated tags, no-show risk scores, lifetime value estimates, and platform activity.',
      '• You are responsible for personal information you collect, store, or process through the Partner Dashboard, including guest CRM data, staff information, guest notes, allergy incident records, and any notes or tags you create about Diners.',
      'The provisions of Sections 10.2 through 10.12 constitute the data processing addendum between the parties for the purpose of PIPEDA, Quebec Law 25, and other applicable Canadian privacy laws. No separate signed DPA is required.',
      '10.2 Your Privacy Obligations',
      "As a data controller, you are responsible for complying with all applicable Canadian privacy laws — including PIPEDA, Quebec Law 25, Canada's Anti-Spam Legislation (CASL), and Alberta and BC PIPA where applicable — in connection with your handling of Diner and staff personal information accessed through the Platform. You must maintain your own privacy policy where required by law.",
      '10.3 Booking Data Shared by Cenaiva',
      "When a Diner makes a Booking through the Platform, Cenaiva shares relevant booking details with you — such as the Diner's name, party size, reservation time, contact information, special requests, allergy notes, the no-show risk score, the lifetime value estimate, and any behavioural tags relevant to hosting the visit — solely to enable you to fulfill the Booking and operate your venue.",
      "You may use Diner information shared by Cenaiva only for managing the Diner's visit, responding to inquiries, and operating loyalty or service-recovery programs to which the Diner has separately consented in compliance with PIPEDA, CASL, and Quebec Law 25.",
      'You may not add Diners to your own marketing lists, send promotional messages, profile Diners for purposes unrelated to their Booking, sell Diner information to third parties, train AI or analytics models for purposes unrelated to your operations, or contact Diners outside the Platform unless you have obtained separate valid consent directly from the Diner. You are solely responsible for obtaining and recording any consents required for your own use of Diner information.',
      '10.4 Staff Accounts, Biometric Authentication, and Sensitive Actions',
      'The Platform offers staff sign-in via biometric authentication (Face ID and Touch ID on iOS, fingerprint on Android) and an optional biometric confirmation step for sensitive operations such as approving transfers and refunds. Biometric processing occurs on the device through Apple or Google APIs; raw biometric data is not transmitted to or stored by Cenaiva.',
      "If your jurisdiction requires consent, notice, or a declaration for the use of biometric authentication by staff (including any declaration to the Commission d'accès à l'information of Quebec for systems Cenaiva makes available), the parties will cooperate to make any required filing. You remain responsible for obtaining staff consent and for any declaration required for biometric data you collect or use independently of the Platform.",
      '10.5 Sub-Processors',
      'Cenaiva engages Sub-Processors to deliver the Platform. The current list of Sub-Processors and the services they provide is set out in Schedule A. Cenaiva imposes contractual data-protection obligations on each Sub-Processor that are no less protective than those in this Agreement.',
      "Cenaiva will give at least 30 days' notice (by email or in the Partner Dashboard) before adding or replacing a Sub-Processor that processes personal information in a materially new way. You may object in writing within 30 days; if the objection cannot be resolved, you may terminate this Agreement and receive a pro-rata refund of prepaid Subscription Fees as your sole remedy.",
      '10.6 Data Residency',
      'Personal information processed under this Agreement is stored primarily in Canada and the United States. Several Sub-Processors may process data in additional jurisdictions, as noted in Schedule A. Cross-border transfers are made subject to contractual safeguards and any consent requirements under applicable law.',
      '10.7 Cenaiva Personnel Access',
      'Cenaiva personnel access to Partner data and Diner data accessible to your restaurant is logged in an append-only audit trail, role-restricted, and limited to support, compliance, security, and quality-review purposes. Cenaiva applies the principle of least privilege and reviews access on a periodic basis.',
      '10.8 Data Security',
      'You agree to implement and maintain reasonable technical and organizational measures to protect Diner and staff personal information accessible through the Partner Dashboard against unauthorized access, disclosure, or misuse.',
      'Cenaiva enforces row-level security on Platform tables, logs sensitive staff actions to an append-only audit trail, sends new-device sign-in alerts to staff with Platform access, runs automated security scans against its database, and encrypts data in transit using TLS. Card data is collected and stored solely by Stripe, a PCI-DSS Level 1 service provider — Cenaiva does not see or store full card numbers, CVVs, or PIN data. Cenaiva will make summary security attestations available on request, subject to a mutual non-disclosure agreement.',
      "Vulnerability disclosure. Suspected security vulnerabilities in the Platform may be reported in good faith to security@cenaiva.com. Cenaiva will not pursue legal action against good-faith security researchers who report vulnerabilities in accordance with this clause, do not access or modify other users' data, and give Cenaiva a reasonable opportunity to remediate before public disclosure.",
      '10.9 Breach Notification',
      'Each party shall notify the other party in writing without unreasonable delay, and in any case within 72 hours, of becoming aware of any actual or reasonably suspected breach of security safeguards affecting personal information processed under this Agreement.',
      'The notification shall include, to the extent then known: the nature of the breach, the categories and approximate number of individuals and records affected, the likely consequences, and the measures taken or proposed to address the breach. The parties shall cooperate in good faith on investigation, mitigation, and any required notifications to individuals or regulators.',
      '10.10 AI and Aggregated Data',
      'Cenaiva may use aggregated, de-identified data derived from Partner Content and Platform usage to train, evaluate, and improve AI features, analytics, and benchmarking products. Partner-identifying information will not be used to train AI models offered to third parties. Diner personal information used in AI features is governed by the consumer Privacy Policy.',
      '10.11 Data Subject Requests',
      'If you receive a request from a Diner to access, correct, delete, or port personal information held by Cenaiva (as distinct from data held by you), you shall forward the request to privacy@cenaiva.com within five (5) Business Days. Cenaiva will respond to the Diner directly within the timelines required by applicable law. You may handle requests concerning data you control independently as the applicable controller.',
      '10.12 Loyalty Program',
      "If and when Cenaiva activates loyalty features, the Diner's loyalty membership is held with Cenaiva, not with you. You may see your venue's contribution to a Diner's loyalty status but may not export, transfer, or independently market to a Diner based on their Cenaiva loyalty data without separate Diner consent obtained outside the Platform.",
    ],
  },
  {
    heading: '11. Intellectual Property',
    paragraphs: [
      "11.1 Cenaiva's Property",
      'All content, software, features, designs, branding, and materials associated with the Platform are owned by Cenaiva or its licensors and are protected by applicable intellectual property laws. This Agreement does not transfer any ownership rights to you. You may not copy, reproduce, modify, reverse-engineer, decompile, scrape, or create derivative works from any part of the Platform.',
      '11.2 Your Content',
      "You retain ownership of all Partner Content. By uploading Partner Content, you grant Cenaiva a non-exclusive, worldwide, royalty-free licence to display, reproduce, host, modify (for formatting purposes), and use your Partner Content within the Platform and in connection with Cenaiva's marketing and promotional activities for the duration of this Agreement.",
      'You represent that you own or have the right to use all Partner Content you upload, and that it does not infringe the rights of any third party.',
      '11.3 Use of Restaurant Name and Marks',
      "You grant Cenaiva a non-exclusive, worldwide, royalty-free licence to use your restaurant's name, logo, trade marks, and publicly available images for the purpose of identifying you as a Restaurant Partner and promoting the Platform during the term of this Agreement. Cenaiva will follow any reasonable brand guidelines you provide. This licence terminates upon expiration or termination of this Agreement, except for materials already produced and in distribution at the time of termination.",
      'Publicity opt-out. Cenaiva will obtain your written consent (email is sufficient) before publishing a case study, named press release, or named investor-relations material that features you. Inclusion in customer lists, "logo walls," and aggregated press counts does not require separate consent.',
      '11.4 Feedback',
      'If you provide feedback, suggestions, or ideas regarding the Platform, you grant Cenaiva a perpetual, irrevocable, worldwide, royalty-free licence to use them for any purpose without obligation to you.',
      '11.5 Cenaiva IP Indemnity',
      'Cenaiva will defend, indemnify, and hold you harmless from third-party claims that the Platform itself, as provided by Cenaiva and used in accordance with this Agreement, infringes a Canadian copyright, trade-mark, or patent, and will pay damages finally awarded by a court or agreed in settlement, subject to the cap in Section 16. This indemnity does not apply to claims arising from Partner Content, your modifications, or your combination of the Platform with materials not provided by Cenaiva.',
      '11.6 Content Moderation',
      "Cenaiva may remove or refuse to display Partner Content that is unlawful, infringing, defamatory, hateful, sexually explicit, or otherwise inconsistent with Cenaiva's content standards. Cenaiva will notify you when content is removed and, where reasonably possible, give you an opportunity to cure.",
    ],
  },
  {
    heading: '12. Confidentiality',
    paragraphs: [
      'Each party agrees to keep confidential any non-public information received from the other party in connection with this Agreement that is reasonably understood to be confidential, including pricing, product roadmaps, business strategies, technical information, and personal information.',
      "Neither party will disclose such information to third parties without the other's prior written consent, except as required by law or to professional advisors bound by equivalent confidentiality obligations.",
      'This obligation does not apply to information that is or becomes publicly available through no fault of the receiving party, was already known to the receiving party without restriction, or that the receiving party independently develops without reference to the confidential information.',
    ],
  },
  {
    heading: '13. Representations and Warranties',
    paragraphs: [
      'You represent and warrant that:',
      '• You are duly authorized to operate your restaurant and to enter into this Agreement.',
      '• All information you provide to Cenaiva is accurate and complete.',
      '• Your restaurant holds all required licences, permits, and regulatory approvals to operate in your jurisdiction.',
      '• Your use of the Platform will comply with all applicable laws.',
      '• You have the right to grant the licences described in this Agreement with respect to your Partner Content.',
      '• You will comply with Canadian accessibility legislation applicable to your in-venue operations, including AODA where applicable.',
      '• You are not located in, ordinarily resident in, or operating from a country or region subject to comprehensive Canadian, U.S., or U.N. sanctions, and you are not listed on any Canadian, U.S., or U.N. restricted-party or sanctions list. You will notify Cenaiva immediately if your status changes.',
      '• Neither you nor any of your representatives has offered, given, or promised, or will offer, give, or promise, anything of value to any Cenaiva employee, contractor, or representative in connection with this Agreement, in violation of the Corruption of Foreign Public Officials Act or any other applicable anti-corruption law.',
    ],
  },
  {
    heading: '14. Suspension, Termination, and Appeal',
    paragraphs: [
      '14.1 Termination by You',
      'You may cancel your subscription at any time by contacting help@cenaiva.com or by removing your restaurant from the Partner Dashboard, which cancels your Stripe subscription at the end of the current Billing Cycle. Cancellation takes effect at the end of the current Billing Cycle. No refund will be issued for the remaining portion of a paid Billing Cycle except as described in Section 5.6.',
      '14.2 Termination by Cenaiva — Minor Violations',
      "For minor violations of this Agreement — including repeated failure to update menu information, consistent failure to honor Bookings without cause, or late payment — Cenaiva will provide 14 days' written notice identifying the issue and requiring remediation. If the issue is not resolved within that period, Cenaiva may suspend or terminate your account.",
      '14.3 Termination by Cenaiva — Serious Violations',
      'Cenaiva may suspend or terminate your account immediately and without notice for serious violations, including but not limited to:',
      '• Fraud, misrepresentation, or deceptive practices toward Diners or Cenaiva',
      '• Misuse of Diner personal data',
      '• Providing false allergen or menu information that causes or risks harm to Diners',
      '• Harassment or abuse of Diners or Cenaiva staff',
      '• Illegal activity conducted through or in connection with the Platform',
      '• Referral program abuse or fee circumvention intended to evade billing',
      '• Breach of sanctions or anti-corruption representations',
      '• Actions that expose Cenaiva to legal, regulatory, or reputational harm',
      '14.4 Appeal',
      'If your account is suspended or terminated under Section 14.2 or 14.3, you may submit a written appeal to legal@cenaiva.com within 14 days of the action. Cenaiva will review the appeal and respond in writing within 14 days of receipt. The decision on appeal is final.',
      '14.5 Effect of Termination',
      'Upon termination:',
      '• Your access to the Platform and Partner Dashboard ceases immediately or at the end of the notice period, as applicable.',
      '• Any outstanding fees owed to Cenaiva become immediately due and payable.',
      '• Refunds are handled as described in Section 5.6.',
      '• Pending Diner Bookings should be honored where possible — you are responsible for communicating directly with affected Diners regarding any Bookings that cannot be fulfilled.',
      '14.6 Survival',
      'The following sections survive termination of this Agreement: 1 (Definitions), 5.6, 5.7, 5.8, 7 (allergen liability), 10 (Data, Privacy, and Security, including 10.9 breach notification), 11 (Intellectual Property), 12 (Confidentiality), 14.5 and 14.6, 15 (Data Export and Deletion), 16 (Limitation of Liability), 17 (Indemnification), 19 (Dispute Resolution), 21 (Governing Law), 22 (Language), 23 (General Provisions), and any other provision that by its nature is intended to survive.',
      '14.7 Termination by Cenaiva — Without Cause',
      "Cenaiva may terminate this Agreement without cause on 60 days' written notice to you. In that event, Cenaiva will refund a pro-rata portion of any prepaid Subscription Fee for the unused portion of the current Billing Cycle as described in Section 5.6.",
    ],
  },
  {
    heading: '15. Data Export and Deletion After Termination',
    paragraphs: [
      'Following termination, you may request an export of your own business data — including your menu content, reservation history, Pre-Order history, and staff account records — by contacting help@cenaiva.com within 30 days of termination. Exports are produced manually by Cenaiva support and will be delivered in a structured, commonly used format such as CSV or JSON. Cenaiva does not currently offer a self-serve export from the Partner Dashboard.',
      'Exported files are retained by Cenaiva for 30 days after delivery and then permanently deleted from Cenaiva systems; you are responsible for downloading and securing the file within that window.',
      'After the 30-day request window, your data will be deleted from our active systems on a rolling schedule, subject to any retention obligations required by law.',
      'You may not request or export Diner personal information such as email addresses, phone numbers, payment data, voice recordings, or Cenaiva-generated profiling data — this information is controlled by Cenaiva under the data controller structure in Section 10 and will not be transferred to you upon termination.',
      'Cenaiva may retain certain records following termination where required for legal, financial, tax, or dispute resolution purposes (generally six years under Canadian tax and consumer protection law), in accordance with applicable law.',
    ],
  },
  {
    heading: '16. Limitation of Liability',
    paragraphs: [
      'To the fullest extent permitted by applicable law:',
      '• Neither party is liable for any indirect, incidental, special, punitive, exemplary, or consequential damages arising from this Agreement or use of the Platform.',
      '• Cenaiva is not responsible for lost revenue, lost Bookings, lost customers, or business interruption arising from Platform downtime, feature changes, or termination.',
      '• Cenaiva is not liable for disputes between you and Diners, including claims related to food quality, allergens, service, or cancellations.',
      "• Each party's total cumulative liability to the other for all claims arising out of or relating to this Agreement shall not exceed the total Subscription Fees you paid to Cenaiva in the 12 months prior to the event giving rise to the claim, or CAD $5,000, whichever is greater.",
      "Exclusions from the cap. The cap above does not apply to: (a) your indemnification obligations under Section 17; (b) either party's breach of confidentiality under Section 12; (c) either party's IP indemnification obligations under Sections 11.5 and 17; (d) fees you owe to Cenaiva under Section 5; or (e) liability that cannot be excluded under applicable Canadian law, including liability for gross negligence or wilful misconduct.",
      'Nothing in this Agreement limits liability that cannot be excluded under applicable Canadian law.',
    ],
  },
  {
    heading: '17. Indemnification',
    paragraphs: [
      'You agree to indemnify, defend, and hold harmless Cenaiva, its officers, employees, contractors, and partners from and against any claims, liabilities, damages, losses, or expenses (including reasonable legal fees) arising from:',
      '• Your use of or inability to use the Platform',
      '• Your violation of this Agreement',
      "• Any claim by a Diner arising from your restaurant's food, service, allergen information, or failure to honor a Booking or Pre-Order",
      '• Any inaccurate, misleading, or harmful menu or allergen information you provided to the Platform',
      '• Your violation of any applicable law or third-party rights',
      '• Any misuse of Diner personal data by you or your staff',
      '• Any breach of Section 6 obligations regarding staff offboarding, competitive use of Diner data, or fee circumvention',
    ],
  },
  {
    heading: '18. Service Availability, Support, and Force Majeure',
    paragraphs: [
      '18.1 Service Availability',
      'Cenaiva aims to provide a reliable platform. However:',
      '• We do not guarantee that the Platform will be available at all times or free from errors.',
      '• We may perform scheduled or emergency maintenance that temporarily affects access — we will endeavour to provide advance notice where reasonably possible.',
      '• We are not liable for losses arising from Platform downtime, outages, or third-party service failures.',
      '• Cenaiva does not offer a service level agreement (SLA), uptime guarantee, or downtime credit mechanism under this Agreement.',
      '18.2 Support Tiers',
      'Cenaiva provides email support at help@cenaiva.com seven days a week, with the following non-binding response targets:',
      '• Critical (Platform unreachable, payment processing down, security incident) — within 4 hours',
      '• High (significant feature broken affecting Bookings) — within 1 Business Day',
      '• Standard — within 2 Business Days',
      'Critical issues should be flagged with a subject line beginning "URGENT —". Response targets may be longer on statutory holidays observed in the Province of Ontario. Cenaiva does not offer phone support under this Agreement.',
      '18.3 Force Majeure',
      'Neither party is liable for any delay or failure to perform resulting from causes beyond its reasonable control, including internet or network outages, third-party service failures (including payment processors and infrastructure providers), natural disasters, acts of government, pandemics, or other events outside reasonable control. Obligations under this Agreement will be suspended for the duration of the event. This clause does not excuse payment obligations for fees already incurred.',
      'Termination for prolonged Force Majeure. If a Force Majeure event continues for more than 60 consecutive days, either party may terminate this Agreement on written notice, and Cenaiva will refund a pro-rata portion of any prepaid Subscription Fee for the unused portion of the current Billing Cycle.',
    ],
  },
  {
    heading: '19. Dispute Resolution',
    paragraphs: [
      'We encourage you to contact us first at help@cenaiva.com to resolve any concerns informally. We will make a genuine effort to respond within 30 days of receiving your complaint.',
      "If a dispute cannot be resolved informally, both parties agree to attempt in good faith to resolve the matter through mediation administered by the ADR Institute of Canada before initiating formal legal proceedings. Quebec partners may instead elect mediation administered by the Institut de médiation et d'arbitrage du Québec. If mediation does not resolve the dispute within 60 days of a written request to mediate, either party may submit the dispute to the exclusive jurisdiction of the courts of the Province of Ontario, subject to any mandatory jurisdictional rights of Quebec partners under applicable Quebec law.",
    ],
  },
  {
    heading: '20. Changes to This Agreement',
    paragraphs: [
      "Cenaiva may update this Agreement from time to time. For minor changes, we will update the \"Last Updated\" date at the top of this document. For material changes — including fee changes — we will provide at least 30 days' written notice via email or in-app notification before the changes take effect. Prior versions remain available at https://cenaiva.com/partners/agreement-history.",
      "A change is material if it increases fees, reduces or removes a feature you actively use, materially changes how Cenaiva uses Diner data shared with you, narrows your data rights, or reduces Cenaiva's data-protection commitments. Bug fixes, UI updates, security improvements, and the addition of optional features are not material changes.",
      'Your continued use of the Platform after the effective date of any changes constitutes acceptance of the updated Agreement. If you do not agree, you may cancel your account before the changes take effect.',
    ],
  },
  {
    heading: '21. Governing Law and Territory',
    paragraphs: [
      'This Agreement is governed by and construed in accordance with the laws of the Province of Ontario and the federal laws of Canada applicable therein, except where the laws of another Canadian province apply mandatorily.',
      'The Platform is currently offered only in Canada. If Cenaiva launches in jurisdictions outside Canada, separate terms will apply to those jurisdictions.',
    ],
  },
  {
    heading: '22. Language / Langue',
    paragraphs: [
      'This Agreement is available in both English and French. For restaurant partners located in Quebec, the French version will be made available first in accordance with the Charter of the French Language, and Quebec partners may request a written copy of the French version at no cost before being bound by the English version. In the event of any conflict between the two versions, the interpretation required by applicable law will apply.',
      "Le présent accord est disponible en anglais et en français. Pour les partenaires restaurateurs situés au Québec, la version française sera mise à disposition en premier, conformément à la Charte de la langue française, et les partenaires québécois peuvent demander une copie écrite de la version française, sans frais, avant d'être liés par la version anglaise. En cas de conflit entre les deux versions, l'interprétation requise par la loi applicable s'appliquera.",
    ],
  },
  {
    heading: '23. General Provisions',
    paragraphs: [
      'Severability. If any provision of this Agreement is found to be unlawful, void, or unenforceable, that provision will be severed and the remaining provisions will continue in full force and effect.',
      "Assignment. Cenaiva may assign this Agreement in connection with a merger, acquisition, financing, or sale of assets without notice to you. You may not assign your rights or obligations under this Agreement without Cenaiva's prior written consent.",
      'Waiver. Our failure to enforce any provision of this Agreement on any occasion does not constitute a waiver of our right to enforce that provision in the future.',
      'Notices. Legal notices to Cenaiva must be sent to legal@cenaiva.com. Notices to you will be sent to the email address associated with your account. Notices are deemed received 24 hours after sending unless a delivery failure is received.',
      'No third-party beneficiaries. This Agreement is between Cenaiva and you only. No Diner or other third party has any right to enforce any provision of this Agreement, except as expressly stated for permitted assigns under this Section 23.',
      "Entire Agreement. This Agreement, together with Schedule A and any order forms or addenda, constitutes the entire agreement between you and Cenaiva with respect to your role as a Restaurant Partner and supersedes all prior agreements or understandings on the same subject matter. This Agreement does not affect or supersede the consumer Terms of Service or Privacy Policy that govern Diners.",
      'Headings. Section headings are included for convenience only and have no interpretive effect.',
      "Independent Contractors. The parties are independent contractors. Nothing in this Agreement creates a partnership, joint venture, agency, or employment relationship between Cenaiva and any restaurant partner, except as expressly stated regarding Cenaiva's role as agent for Deposit collection under Section 5.2.",
    ],
  },
  {
    heading: '24. Contact',
    paragraphs: [
      '• Support: help@cenaiva.com',
      '• Privacy: privacy@cenaiva.com',
      '• Legal: legal@cenaiva.com',
      '• Security: security@cenaiva.com',
      '• Website: https://cenaiva.com/partners',
      'Support is available in English and French. Le soutien est offert en anglais et en français.',
    ],
  },
];

/**
 * Schedule A — same 13 sub-processors as the Privacy Policy. We keep
 * a parallel array here for fidelity with the canonical doc; if the
 * lists ever diverge they shouldn't, but having them as separate
 * exports lets the screen render the partner-voice copy alongside.
 */
export const PARTNER_AGREEMENT_SUB_PROCESSORS: SubProcessor[] = [
  {
    name: 'Supabase',
    service: 'Database, authentication, edge functions',
    region: 'United States, with regional options',
  },
  {
    name: 'Stripe / Stripe Canada',
    service: 'Payment processing, saved cards, invoicing',
    region: 'Canada, United States',
  },
  {
    name: 'OpenAI',
    service: 'AI language understanding and vision (receipts)',
    region: 'United States',
  },
  {
    name: 'ElevenLabs',
    service: 'Text-to-speech voice synthesis',
    region: 'United States',
  },
  {
    name: 'Deepgram',
    service: 'Speech-to-text transcription',
    region: 'United States',
  },
  {
    name: 'Twilio',
    service: 'SMS messaging and one-time passcodes',
    region: 'United States',
  },
  {
    name: 'Resend',
    service: 'Transactional email',
    region: 'United States',
  },
  {
    name: 'Expo (EAS)',
    service: 'Mobile app delivery and push notifications',
    region: 'United States',
  },
  {
    name: 'PostHog',
    service: 'Product analytics and usage insights',
    region: 'United States, European Union',
  },
  {
    name: 'Sentry',
    service: 'Error monitoring and crash reporting',
    region: 'United States',
  },
  {
    name: 'Vercel',
    service: 'Web hosting and infrastructure',
    region: 'United States, global edge',
  },
  {
    name: 'Google LLC',
    service: 'Google OAuth sign-in, Google Maps Platform, on-device speech (Android), Android push',
    region: 'United States',
  },
  {
    name: 'Apple Inc.',
    service: 'Sign in with Apple, on-device speech (iOS), iOS push',
    region: 'United States',
  },
];

/**
 * Restaurant Partner Agreement version history. Surfaced on the
 * Agreement History screen. Append a row when a new version ships.
 */
export const PARTNER_AGREEMENT_HISTORY: AgreementHistoryEntry[] = [
  {
    version: '2.1',
    effectiveDate: 'May 21, 2026',
    summary:
      'Initial mobile-shipped version. Defines fee structure ($199.99/month + $1.00/booking + 5.5% pre-order), Trial Period (first 500 partners get 3 months free), data controller structure, sub-processor list, and dispute resolution via ADR Institute of Canada.',
  },
];
